### ISSUE TITLE
[AUTH] Hotfix/ajustar e testar app.py

### ISSUE THREAD

**Issue by rafaelrubira2** [paft-inc/paft-microservices#47]
Ref. [AUTH] Criar endpoint de Login #22

Ajustar arquivo app.py

Esse comando deveria funcionar normalmente:
```bash
curl \
    --data '{"usuario":"aluno","senha":"123"}' \
    -H "Content-Type: application/json" \
    -X POST \
    localhost:3000/login
```

Porém está retornando erro 500 !

**Comment by rafaelrubira2** [comment]
Erro:
127.0.0.1 - - [03/Dec/2022 14:38:56] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/Curso_DevOps/aula_dynatrace/paft-microservices/auth/app.py", line 27, in login
    if users_data[usuario] == senha:
KeyError: 'aluno'
